### ISSUE TITLE
The "se" lang code should be an option to the "sv" lang code

### ISSUE THREAD

**Issue by hentor5** [Hypixel-Translators/hypixel-translators-bot#161]
The "se" lang code should be an option to the "sv" lang code. They are easily mixed-up and most swedes use "se" since that's what er use for websites (.se).

**Comment by ImRodry** [comment]
With the current system we have, we can only use either sv or se and we chose to use sv because it's what crowdin uses and I believe that's the official language code. If you'd like us to permanently change this, we can look into it with other swedish people.
