### ISSUE TITLE
Channel whitelist command

### ISSUE THREAD

**Issue by TheComputer8423** [Hypixel-Translators/hypixel-translators-bot#174]
Command to whitelist a channel for bot use without having to go into the code and manually adding it each time

**Comment by QkeleQ10** [comment]
No progress D:

**Comment by ImRodry** [comment]
Hey! Now that we can start working on this, I'd like to ask you this: would you prefer to have 2 commands one for whitelist and one for blacklist or have it all in one? If it's the latter, how would the syntax be?

**Comment by TheComputer8423** [comment]
One would probably be better, and if +channel isn't used it could be "+channel whitelist/blacklist #channel"

**Comment by ImRodry** [comment]
When the idea for this command came up it sounded good but it seems like it would bring more issues than those that it would solve. Those issues being increased delays, difficult logistics with the command and it's not needed anymore. Whitelists and blacklists aren't updated that often to justify making its own command so I'll close this for now.
