### ISSUE TITLE
+languagestats, +langstats, +lstats

### ISSUE THREAD

**Issue by QkeleQ10** [Hypixel-Translators/hypixel-translators-bot#223]
**Is your feature request related to a problem? Please describe.**
No, otherwise I'd have submitted a bug report.

**Describe the solution you'd like**
A command `+languagestats <language code>` which shows the progress in the specified language for all associated projects, if the language exists in that project.

**Describe alternatives you've considered**
Again, this is not a bug report.

**Additional context**
No.

**Comment by QkeleQ10** [comment]
I hate this template.

**Comment by ImRodry** [comment]
Never really thought this template through tbf, but thanks for the suggestion. This is what the biscuit translations bot used to do which was recently removed so I'd like to add it's features to the bot, and this is one of them, thanks for the suggestion!

**Comment by QkeleQ10** [comment]
it's

**Comment by QkeleQ10** [comment]
Anyways, great! Thanks :D

**Comment by ImRodry** [comment]
Command has been added and will be deployed to the bot soon.
