### ISSUE TITLE
[REQUEST]  Annual Medals for Translators

### ISSUE THREAD

**Issue by iBieelG** [Hypixel-Translators/hypixel-translators-bot#308]
**Please describe the feature you want to see added with as much detail as possible.**
A system where translators (from any project that is linked to the Hypixel Translator Community) receive secondary tags on the discord server annually as an achievement for collaborating to improve and improve Hypixel translation in general.

**Describe how you want that feature to work**
The member who reaches 1 year after his / her application is accepted in the team, will receive this position automatically.

**Describe alternatives you've considered**
The only alternative to this system would be when that member left the project, he would lose the position of translator, but his time schedule would continue to demonstrate the work and role he played in the community. And if it reaches another year in the team, the old tag would be removed so as not to accumulate many positions.

**Additional context**
Add any other information or screenshots about the feature request. Don't forget that you can upload images on GitHub!
![Screenshot_1](https://user-images.githubusercontent.com/83674580/117076113-48f28c00-ad0c-11eb-8d6b-bb81fe6c636c.png)
1 year - 🥇

![image](https://user-images.githubusercontent.com/83674580/117076515-e5b52980-ad0c-11eb-9cc3-94a802bc1935.png)
2 years - 🥈

![image](https://user-images.githubusercontent.com/83674580/117076587-febdda80-ad0c-11eb-8019-8e7b623ccb6e.png)
3 years - 🥉

![image](https://user-images.githubusercontent.com/83674580/117076629-11381400-ad0d-11eb-8314-569a63e448a4.png)
4 years - 🏅

![image](https://user-images.githubusercontent.com/83674580/117076743-50666500-ad0d-11eb-88cf-21d1bb05d46f.png)
5 years - 🎖️

![image](https://user-images.githubusercontent.com/83674580/117076796-696f1600-ad0d-11eb-96f7-faa6300325d6.png)
6 years - 🏆

**Comment by ImRodry** [comment]
Thanks for the suggestion! I'll definitely consider this and a way to constantly update these roles but I believe we'll only be doing this for Hypixel translators as that is the main focus of our server (and also the oldest project, therefore it is likely to be the oldest project for most people) but that will be discussed with the team. Will notify you when there is progress to this!

**Comment by ImRodry** [comment]
Although this is not extremely complicated, it will take a slight rework of the verification system and I do not have that much time at the moment so I’m reducing the priority on this. You can expect to see developments on this after the beginning of July.
