### ISSUE TITLE
[REQUEST] mc/skin and mc/lookup commands

### ISSUE THREAD

**Issue by ArrivedBog593** [Hypixel-Translators/hypixel-translators-bot#309]
**Please describe the feature you want to see added with as much detail as possible.**
I would like them to add something similar to the minecraft bot's mc/skin and mc/lookup commands

**Describe how you want that feature to work**
The command mc/skin (player) shows the current skin of a Minecraft user
And the command mc/lookup (player) shows the previous nicknames and current nickname of a minecraft user

**Additional context**
mc/skin command
![image](https://user-images.githubusercontent.com/71849488/117080019-32433980-acfa-11eb-98b6-da7008d80c00.png)
mc/lookup command
![image](https://user-images.githubusercontent.com/71849488/117080072-57d04300-acfa-11eb-8326-8050f99fa700.png)

**Comment by ImRodry** [comment]
I’d like to explore what the MC API has to offer and probably make a general +mc command with all those subcommands (possibly one to get the UUID although I’m not too sure about that one)

**Comment by ChachyDev** [comment]
You'd be looking at these probably then:
https://wiki.vg/Mojang_API#UUID_to_Name_History
https://wiki.vg/Mojang_API#Username_to_UUID
https://crafatar.com/#body-renders

**Comment by ImRodry** [comment]
Updating this to let you know that command development will resume once #320 is finished and merged. We wanna focus all efforts on that PR for now and then start adding more commands after that

**Comment by ChachyDev** [comment]
> You'd be looking at these then:
> https://wiki.vg/Mojang_API#UUID_to_Name_History
> https://wiki.vg/Mojang_API#Username_to_UUID
> https://crafatar.com/#body-renders

To respond with the confusion face, I meant the apis to use since you seemed rather confused if the Mojang API offered Username -> UUID.

**Comment by ImRodry** [comment]
I know that exists and we’re already using that in a command. I said I wasn’t too sure if I would implement it because I don’t see why any user would need the UUID of someone else on a day-to-day basis
