### ISSUE TITLE
/languagestats not working

### ISSUE THREAD

**Issue by NotAkih** [Hypixel-Translators/hypixel-translators-bot#748]
### Issue Description

Issue: can't see the language statistics for PT-BR (I believe this happens with every language not in the slash command list)
Steps:
1. Just try to `/languagestats` a language that is not listed in the slash command suggestions, this didn't work for PT and PT-BR

### Expected result

The language statistics

### Actual result

A error saying "That language couldn't be found!"

### Your roles on the server

- Portuguese Brazilian Translator
- Hypixel Translator
- SkyblockAddons Translator
- Quickplay Translator
- Bot Translator
- 1 Year Veteran
- MVP+
- Verified
- Crowdin Updates

**Comment by ImRodry** [comment]
Seems like the bot just hadn't updated, this issue was fixed as of https://github.com/Hypixel-Translators/hypixel-translators-bot/commit/b3abcd70cea675b3c11992d6ce3ae901715d1802
